# Generated by Django 5.1.3 on 2024-12-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashbord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_task', models.PositiveIntegerField(default=0)),
                ('completed_task', models.PositiveIntegerField(default=0)),
                ('pending_task', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
